name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js 18.x
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: install dependencies
      - uses: bahmutov/npm-install@v1

      - name: Build web-app
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3